image:
  - Visual Studio 2022
  - Ubuntu
  - macOS

version: 5.4.1-{build}

test: off

skip_commits:
  message: /noci .*/

build_script:
  - dotnet test -f netcoreapp3.1 -c:Release test/DryIoc.CommonServiceLocator.UnitTests/DryIoc.CommonServiceLocator.UnitTests.csproj
  - dotnet test -f netcoreapp3.1 -c:Release test/DryIoc.Microsoft.DependencyInjection.Specification.Tests/DryIoc.Microsoft.DependencyInjection.Specification.Tests.csproj

  - dotnet test -f net7.0 -c:Release docs/DryIoc.Docs/DryIoc.Docs.csproj
  - dotnet test -f net7.0 -c:Release test/DryIoc.UnitTests/DryIoc.UnitTests.csproj
  - dotnet test -f net7.0 -c:Release test/DryIoc.IssuesTests/DryIoc.IssuesTests.csproj
  - dotnet test -f net7.0 -c:Release test/DryIoc.Microsoft.DependencyInjection.Specification.Tests/DryIoc.Microsoft.DependencyInjection.Specification.Tests.csproj

for:
  - matrix:
      only:
        - image: Visual Studio 2022

    build_script:
      - build_with_packaging.bat

    artifacts:
      - path: .\.dist\packages\*.nupkg
